name: self-hosted-check

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    runs-on:
      - self-hosted
      - linux
      - x64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validar projeto
        run: |
          chmod +x scripts/*.sh
          ./scripts/check-project.sh
